// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: demo.sql

package db

import (
	"context"
)

const setDemoCoverage = `-- name: SetDemoCoverage :exec
UPDATE settings SET value = ?1
WHERE key IN ('usage.daily.started_at', 'usage.hourly.started_at')
`

// Only the disposable demo runtime backdates its synthetic usage coverage.
func (q *Queries) SetDemoCoverage(ctx context.Context, startedAt string) error {
	_, err := q.db.ExecContext(ctx, setDemoCoverage, startedAt)
	return err
}
